<?php

namespace AppBundle\Repository;

/**
 * cartsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cartsRepository extends \Doctrine\ORM\EntityRepository
{
}
